### PR TITLE
Run poetry lock

### PR DESCRIPTION
**Pull request by rusheb**
Addresses #177

### CODE REVIEW

**Review by alan-cooney — APPROVED** [review]

**Review by alan-cooney — CHANGES_REQUESTED** [review]
Are you able to re-run with the latest changes in main? I'll review and merge once done

**Comment by rusheb** [comment]
Hi @alan-cooney, any idea why the check failed? The error seems to be "ConnectionError":
```
 _______ ERROR collecting transformer_lens/tests/test_cache_hook_names.py _______
../../../.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/transformers/utils/hub.py:409: in cached_file
    resolved_file = hf_hub_download(
../../../.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py:124: in _inner_fn
    return fn(*args, **kwargs)
../../../.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py:1212: in hf_hub_download
    raise LocalEntryNotFoundError(
E   huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.
```

Not sure whether this would be related to updating dependencies? Is there a way to re-run the check?

I will also attempt to run the tests locally.

**Comment by rusheb** [comment]
Tests pass for me locally. Test output:
```
❯ poetry run pytest transformer_lens/tests/
===================================================== test session starts =====================================================
platform darwin -- Python 3.9.16, pytest-7.2.1, pluggy-1.0.0
rootdir: /Users/rusheb/code/TransformerLens
plugins: jaxtyping-0.2.12, typeguard-2.13.3, cov-4.0.0, anyio-3.6.2
collected 29 items

transformer_lens/tests/test_cache_hook_names.py .                                                                       [  3%]
transformer_lens/tests/test_d_vocab.py ....                                                                             [ 17%]
transformer_lens/tests/test_hook_tokens.py .                                                                            [ 20%]
transformer_lens/tests/test_hooks.py ....                                                                               [ 34%]
transformer_lens/tests/test_stop_at_layer.py .......                                                                    [ 58%]
transformer_lens/tests/test_tokenizer_special_tokens.py .                                                               [ 62%]
transformer_lens/tests/test_transformer_lens.py ...........                                                             [100%]

====================================================== warnings summary =======================================================

... [ warnings removed for brevity ] ...

========================================= 29 passed, 11 warnings in 79.46s (0:01:19) =========================================
```

env info:
```
❯ poetry env info

Virtualenv
Python:         3.9.16
Implementation: CPython
Path:           /Users/rusheb/code/TransformerLens/.venv
Executable:     /Users/rusheb/code/TransformerLens/.venv/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.9.16
Path:       /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9
Executable: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/python3.9
```

**Comment by rusheb** [comment]
On running, it looks like the checks have passed. 

Would you like me to raise an issue for the previous error?

**Comment by alan-cooney** [comment]
> It looks like the checks have passed on re-running.
> 
> 
> 
> Would you like me to raise an issue for the previous error? 

Thanks! I think it's fine - Looks like it was caused by a GitHub action outage

**Review by alan-cooney — APPROVED** [review]

**Comment by alan-cooney** [comment]
Thanks for the PR! I've merged it in now

**Pull request merged**
