### PR TITLE
Standardize black line length to 100, in line with other project settings

### PR DESCRIPTION
**Pull request by Chanlaw**
# Description

Updates black to use line length 100, in line with the evenbettertoml and rewrap column width settings. 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Screenshots
Please attach before and after screenshots of the change if applicable.

#### Before
Screenshot 2024-04-08 at 1 35 32 PM

#### After
Screenshot 2024-04-08 at 1 33 48 PM

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not rewritten tests relating to key interfaces which would affect backward compatibility

### CODE REVIEW

**Comment by bryce13950** [comment]
Have you discussed making this formatting change with anyone prior to the PR?

**Comment by Chanlaw** [comment]
I spoke with Joseph Bloom about this, but yeah, maybe I should have a public convo on Slack or in GH issues

**Comment by bryce13950** [comment]
No worries. I was just curious if there was a previous conversation about this with anyone who is relatively active on the project. I am in favor of having this limit enforced, but enforcing these sorts of code styling rules can sometimes open debates. 
I had a slightly botched merge on my side that is causing issues now. I will resolve those issues, and make sure this is up to date with the most recent main branch. After that, I will just leave this open for a bit to see if anyone objects to this being enforced.

**Comment by bryce13950** [comment]
👍

**Pull request merged**
