### PR TITLE
Induction heads phase changes demo

### PR DESCRIPTION
**Pull request by ckkissane**
Hey @neelnanda-io , I recently used this library to reproduce some of the phase change results from argument 1 of the induction heads paper. I noticed #108, so I'm happy to contribute if this would be a useful demo. The colab link is here: https://colab.research.google.com/github/ckkissane/TransformerLens/blob/induction-head-demo/Induction_Heads_Demo.ipynb

Also happy to improve it based on any feedback you have (especially for the PCA section). Thanks!

### CODE REVIEW

**Comment by neelnanda-io** [comment]
This is a cool project, thanks for sharing! Nice to see the results at
least vaguely holding up. It would be nice to have a gallery section to
have user contributed demos, though I'm not sure whether the best design is
to have it as a folder on the main demo vs a list in the README linking to
externally hosted projects (I would rather not eg have you need to make a
PR any time you want to update the project!). Thoughts on what feels best
here?

The PCA code seems reasonable to me

Some data presentation tips:
IMO most of your graphs need a log scale x axis, since almost all the
points are compressed on the LHS
The PCA plots would look better with arrows or dotted lines between
adjacent points, and coloured by tokens seen (maybe log tokens seen) idk
how much of a pain that is
It would be good to add a bar to the plots shading the induction head phase
change, the MVP would be doing add_vline at the start and end, and making
it a faint dotted line
The text about loading models and the loading bars are somewhat annoying
and break up the plots. This is probably my fault, but it would be nice to
eg save the plotted data and do it all in the next cell.

But yeah, thanks for making it, and it's cool to see people using TL in the
wild! I'd love to hear feedback on your experience - what the most useful
features of the library were, how this compared to what you'd have done if
TL didn't exist, any pain points, and any features that should really exist
but currently don't.

**Comment by ckkissane** [comment]
Thanks for the feedback! I updated the [notebook](https://colab.research.google.com/github/ckkissane/induction-heads-transformer-lens/blob/main/Induction_Heads_Phase_Change.ipynb) based on your comments. Happy to hear any additional suggestions!

> It would be nice to have a gallery section to have user contributed demos, though I'm not sure whether the best design is to have it as a folder on the main demo vs a list in the README linking to externally hosted projects (I would rather not eg have you need to make a PR any time you want to update the project!). Thoughts on what feels best here? 

I agree that references to externally hosted projects sounds better. I modified this PR to add an examples page inspired by [PyTorch examples](https://github.com/pytorch/examples). Let me know what you think.

> I'd love to hear feedback on your experience - what the most useful features of the library were, how this compared to what you'd have done if TL didn't exist, any pain points, and any features that should really exist but currently don't.

I'm a big fan of this library! I've wanted to play around with the induction heads paper for a while, but was intimidated by the 10B+ token training runs. TL really helped lower the activation energy for me to start the project. 

Honestly, not many pain points. I was able to adapt a lot of the main demo code for my purposes which was helpful. I think having faster loading of the checkpoints would be nice to tighten feedback loops, but not sure how easy that is to optimize.

**Comment by neelnanda-io** [comment]
Thanks! IMO it's better to link to the Colab, and I'm pro keeping examples front and center by having a section in the README - I want the library to feel usable and accessible, and to make it feel obvious that this is actually used by people! (I may revise this if I get _too_ many examples, but feels fine for <10 examples)

```
## Gallery

User contributed examples of the library being used in action:
* [Induction Heads Phase Change Replication](LINK TO COLAB): A partial replication of [In-Context Learning and Induction Heads](PAPER LINK) from YOUR NAME
```

**Comment by ckkissane** [comment]
Sounds good. Updated in the latest commit.

**Comment by neelnanda-io** [comment]
LGTM!

**Pull request merged**
