### PR TITLE
Add get_basic_config util function

### PR DESCRIPTION
**Pull request by adamyedidia**
# Description

Add a util to just output the key hyperparams from the config object returned by `loading_from_pretrained.get_pretrained_model_config`

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots
Please attach before and after screenshots of the change if applicable.

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have not rewritten tests relating to key interfaces which would affect backward compatibility

### CODE REVIEW

**Comment by jbloomAus** [comment]
I'm not sure what this PR is supposed to be doing/solving. Can you please provide some context?

**Comment by adamyedidia** [comment]
> I'm not sure what this PR is supposed to be doing/solving. Can you please provide some context?

Ah, sorry, Neel requested a util that would return just the key hyperparams from the config object returned by `loading_from_pretrained.get_pretrained_model_config` in a dataclass

**Comment by jbloomAus** [comment]
Ok, that's fine. Thanks. Please link the issue in the future :)

**Comment by neelnanda-io** [comment]
I didn't make am issue lol, this on me

**Pull request merged**
