### PR TITLE
Refactor hook_points

### PR DESCRIPTION
**Pull request by VasilGeorgiev39**
# Description

As I was extending get_caching_hooks for #465 I had to keep adding duplicate code to save_hook() and save_hook_back() so I combined them into the same function. Similarly I also removed some duplicate code in add_hook()

## Type of change

- [x] Refactor (does not change functionality)

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not rewritten tests relating to key interfaces which would affect backward compatibility

### CODE REVIEW

**Comment by bryce13950** [comment]
@VasilGeorgiev39 There has been quite a bit of action in this file since you submitted your PR. I am in the middle of getting it up to date with the main branch. The actual merge has turned into a very manual process due to this having been touched so much, but when I am done with that, if you have time to give it a once over, I can then get this in next.

**Comment by bryce13950** [comment]
@VasilGeorgiev39 Alright, so it should be all up to date. After going through it in detail, it looks like the changes you did on the three different blocks are now only relevant to the first two. The third one looks to already have what you did there. I am not sure if you did this or not in another PR, but what is on that third block is very similar to what you had, with some changes made to the logic. The two blocks you refactored have been restored, and I think they are all ready to merge, but I will wait for you to take a look to double check that I didn't miss anything.

**Review by bryce13950 — APPROVED** [review]
I went ahead and double checked it, and I think we are all good to merge. Thanks for making this change!

**Comment by VasilGeorgiev39** [comment]
Thanks for merging! I also just checked it and seems good to me too. Actually it seemed to me that initially I made a mistake in add_hook where in the 'prepend' case I was always adding the hook to the forward hooks but you have fixed this, thanks. I am actually surprised that no tests caught this?

**Comment by bryce13950** [comment]
@VasilGeorgiev39 One of my pending task on getting this project up to date is to run a code coverage report, and add publishing it to the GitHub actions flow. I have not run a code coverage report on this project in probably 8 months, so I cannot tell you definitively what is going on in that respect. I would guess that either the block is not covered at all, or the coverage is suboptimal. If you want to write a test that would improve that coverage, it would be greatly appreciated. In either case, I will open an issue to note this missing coverage.

**Pull request merged**
