### PR TITLE
Add tests to the CD

### PR DESCRIPTION
**Pull request by alan-cooney**
- Adds automatic testing
 - Adds automatic deployment to PyPi, when a release is labelled `major`, `minor` or `patch` (and updates the version with a commit to main)

__Note__: There is a PyPi naming clash, so we're currently waiting to see if we can gain ownership of this name.

### CODE REVIEW

**Comment by neelnanda-io** [comment]
@alan-cooney Did anything end up happening with this?

**Comment by alan-cooney** [comment]
Had to change a few things to get it to pass. I've also disabled `mypy` type checking as currently there are a lot of typing errors that would need to be fixed.

**Comment by alan-cooney** [comment]
@neelnanda-io ready now - I suggest we rebase merge (rather than squash) given the commits do quite different things

**Comment by neelnanda-io** [comment]
Note that this now has a merge conflict with setup.py

How do I rebase merge rather than squash merge from the Github UI?

**Comment by alan-cooney** [comment]
> How do I rebase merge rather than squash merge from the Github UI?

Click on the drop down next to "Merge pull request" and then "Rebase and merge". 

Btw, generally people prefer to keep a "linear history" rather than having a lot of overlapping merges. You can force this with settings -> branch -> main -> require linear history. Then just choose squash merge 95% of the time, and occasionally rebase merge if you want to keep the underlying separate commits within the PR

**Comment by smithjessk** [comment]
🙌

**Comment by alan-cooney** [comment]
@neelnanda-io This is safe to merge now (I've disabled the release part until the package naming is fixed)

**Comment by alan-cooney** [comment]
Closing as there are lots of changes with the renamed files

**Pull request closed without merging**
