### PR TITLE
added support for other pythia 160m seeds

### PR DESCRIPTION
**Pull request by will-hath**
# Description

I think I fixed whatever was causing the merge conflict. Added support for pythia-160m seeds 1, 2, 3

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not rewritten tests relating to key interfaces which would affect backward compatibility

### CODE REVIEW

**Comment by jbloomAus** [comment]
@will-hath  is this still a WIP?

**Comment by will-hath** [comment]
﻿Things should be good

From: Joseph Bloom ***@***.***>
Date: Sunday, August 20, 2023 at 4:57 PM
To: neelnanda-io/TransformerLens ***@***.***>
Cc: Will O Hathaway ***@***.***>, Mention ***@***.***>
Subject: Re: [neelnanda-io/TransformerLens] added support for other pythia 160m seeds (PR #361)

@will-hath<https://github.com/will-hath> is this still a WIP?

**Comment by neelnanda-io** [comment]
@will-hath Can you remove the poetry.lock changes? Otherwise this LGTM

**Comment by neelnanda-io** [comment]
Note that this is still classified as a draft PR, so we can't merge it in

**Pull request closed without merging**
