### PR TITLE
Loading of huggingface 4-bit quantized Llama

### PR DESCRIPTION
**Pull request by coolvision**
# Description

Adding support for loading HF Llama models, 4-bit quantized with bitsandbytes.
This allows to load Llama2-7b into 5-6G of GPU RAM.
Demo or running in in colab on T4 GPU:
https://github.com/coolvision/TransformerLens/blob/llama_4bit_v2/demos/LLaMA2_GPU_quantized.ipynb

The quantization is triggered by setting `load_in_4bit=True` in huggingface `from_pretrained` method.
Then, quantized model should be passed to TransformerLens `from_pretrained`.

```
LLAMA_2_7B_CHAT_PATH = "meta-llama/Llama-2-7b-chat-hf"
inference_dtype = torch.float32

hf_model = AutoModelForCausalLM.from_pretrained(LLAMA_2_7B_CHAT_PATH,
                                             torch_dtype=inference_dtype,
                                             device_map = "cuda:0",
                                             load_in_4bit=True)

tokenizer = AutoTokenizer.from_pretrained(LLAMA_2_7B_CHAT_PATH)

model = HookedTransformer.from_pretrained(LLAMA_2_7B_CHAT_PATH,
                                             hf_model=hf_model,
                                             dtype=inference_dtype,
                                             fold_ln=False,
                                             fold_value_biases=False,
                                             center_writing_weights=False,
                                             center_unembed=False,
                                             tokenizer=tokenizer)
```

This feature requires `torch >= 2.1.1`, `bitsandbytes` & `accelerate` packages:
```
poetry source add --priority=supplemental torch https://download.pytorch.org/whl/cu118
poetry add torch==2.1.1+cu118 --source torch
pip install bitsandbytes
pip install accelerate
```

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have not rewritten tests relating to key interfaces which would affect backward compatibility

### CODE REVIEW

**Comment by msakarvadia** [comment]
Are there any updates on this PR?

**Comment by bryce13950** [comment]
There have been some pretty big changes to the code base since this was opened regarding typing. Those changes are now causing this PR to fail. @coolvision, @msakarvadia if either of you have time to go through the issues and resolve them, that would be great, and I can look at getting this into the main branch. 

I have been going through all of the PRs, and closing whatever I can. Once I am done with that, I will return to the remaining PRs to get them wrapped up. This is pretty high impact one, so I expect that I will return to this first, but if either of you have time to make those changes, I can then get it merged very quickly.

**Comment by hannamw** [comment]
Hi - I'm also interested in this PR. The typing issues seem pretty minor; I can push changes—just a couple of asserts—that will make mypy happy. 

That said, when I actually try to load `meta-llama/Llama-2-7b-chat-hf` in the demo notebook (`demos/LLaMA2_GPU_quantized.ipynb`), I encounter size mismatch errors in `load_state_dict`. It looks like the quantized attention weights are of size `(n, 1)`, while the `state_dict` sizes are `(n_attn_heads, 1, n/n_attn_heads)`. Not sure if this is an issue on my end, or if something else has broken since the notebook was developed

**Comment by bryce13950** [comment]
@hannamw As luck would have it, I am actually right in the middle of auditing all of the demos. I would be happy to take a look at the one here once I am done with the last couple I am currently working through. If you can get the typing changes wrapped up, I should be able to check out the demo before the end of the week, and whenever we both wrap up these two sides, we can get this closed and merged. I'll let you know what I find with the demo once I figure out what happened there.

**Comment by hannamw** [comment]
Great! I'd happily push those typing fixes to this branch, but (maybe because I haven't contributed to TransformerLens before), I don't have push access to `coolvision:llama_4bit_v2`. Do you know what I'd need to do to get access?

**Comment by bryce13950** [comment]
https://github.com/neelnanda-io/TransformerLens/tree/llama_4bit_v2 I setup a branch on the main repo for this. If you want to just submit a separate pull request to that branch for these typing changes, I will then make sure to merge the changes into this PR, and get everything merged into main properly.

**Comment by bryce13950** [comment]
Well @hannamw @msakarvadia, and @coolvision we are just about ready to merge, but we unfortunately cannot do so due to this issue https://github.com/neelnanda-io/TransformerLens/issues/548. Once that is resolved, this can be closed out. If you are anxious to use this before then, simply point your install to this branch, and everything should work just fine.

**Comment by bryce13950** [comment]
All set!

**Comment by winnieyangwannan** [comment]
Hi @bryce13950 , it seems that many of us are still experiencing problems loading the Llama 2 and 3 models  (with quantization). See issues here  #569 #575 . I am wondering if might have time to take a look? Thank you very much 😄

**Pull request merged**
