### PR TITLE
In run_with_hooks, remove hooks, even when an error is thrown.

### PR DESCRIPTION
**Pull request by joelburget**

### CODE REVIEW

**Comment by Stefan-Heimersheim** [comment]
Here's my (old) example of demonstrating the bug, gonna test this PR now!

```
from easy_transformer import EasyTransformer
model = EasyTransformer.from_pretrained("attn-only-1l")

# This fails
def patch(activations, hook):
    activations[:, -1, 2, 3, 4] = 0
    return activations
logits2 = model.run_with_hooks("test", fwd_hooks=[("blocks.0.hook_resid_pre", patch)])

# This still fails
def patch2(activations, hook):
    activations[:, -1, :] = 0
    return activations
logits2 = model.run_with_hooks("test", fwd_hooks=[("blocks.0.hook_resid_pre", patch2)])

# This finally works
model.reset_hooks()
def patch2(activations, hook):
    activations[:, -1, :] = 0
    return activations
logits2 = model.run_with_hooks("test", fwd_hooks=[("blocks.0.hook_resid_pre", patch2)])
```

**Comment by joelburget** [comment]
Note: All lines were just indented, with the exception of `out = ...; return out` being changed to one line.

**Comment by joelburget** [comment]
Test:

```
from transformer_lens import HookedTransformer

model = HookedTransformer.from_pretrained("attn-only-1l")

# hook which fails
def patch(activations, hook):
    activations[:, -1, 2, 3, 4] = 0
    return activations

try:
    logits = model.run_with_hooks(
        "test", fwd_hooks=[("blocks.0.hook_resid_pre", patch)]
    )
except Exception:
    pass

# hook which should pass
def patch2(activations, hook):
    activations[:, -1, :] = 0
    return activations

logits2 = model.run_with_hooks("test", fwd_hooks=[("blocks.0.hook_resid_pre", patch2)])
```

Before:
```
env ❯ python3 test.py
Loaded pretrained model attn-only-1l into HookedTransformer
Traceback (most recent call last):
  File "/Users/joel/code/github/TransformerLens/test.py", line 24, in <module>
    logits2 = model.run_with_hooks("test", fwd_hooks=[("blocks.0.hook_resid_pre", patch2)])
  File "/Users/joel/code/github/TransformerLens/transformer_lens/hook_points.py", line 189, in run_with_hooks
    out = self.forward(*model_args, **model_kwargs)
  File "/Users/joel/code/github/TransformerLens/transformer_lens/HookedTransformer.py", line 291, in forward
    residual = block(
  File "/Users/joel/code/github/TransformerLens/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/joel/code/github/TransformerLens/transformer_lens/components.py", line 702, in forward
    resid_pre = self.hook_resid_pre(resid_pre)  # [batch, pos, d_model]
  File "/Users/joel/code/github/TransformerLens/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1215, in _call_impl
    hook_result = hook(self, input, result)
  File "/Users/joel/code/github/TransformerLens/transformer_lens/hook_points.py", line 48, in full_hook
    return hook(module_output, hook=self)
  File "/Users/joel/code/github/TransformerLens/test.py", line 7, in patch
    activations[:, -1, 2, 3, 4] = 0
IndexError: too many indices for tensor of dimension 3
```

After:
```
env ❯ python3 test.py
Loaded pretrained model attn-only-1l into HookedTransformer
```

**Comment by neelnanda-io** [comment]
LGTM, thanks!

**Pull request merged**
