### PR TITLE
Add helper enum for torch typing

### PR DESCRIPTION
**Pull request by dkamm**
Related to #130 

Adds a helper enum to get mypy to work with torch typing

I've basically copied every name into the enum, except I've replaced instances of `position` with `pos`

I also opted for lower case instead of upper because it felt more visually consistent

Some thoughts:

- rename `head_index` -> `head`?
- rename `d_vocab` -> `n_vocab`?
- use `head` in place of `n_heads`?
- I can see potential for a proliferation of names in this enum (can cross that bridge when we get there)

### CODE REVIEW

**Comment by neelnanda-io** [comment]
Thanks! As ism this fails all the tests,, because `T.batch` is an enum type, not a string. And I don't really get how the add method is supposed to work. But changing it to this seems to pass the tests (I feel like it should subclass _something_, but idk how best to achieve "a class where every attribute is fixed _and_ is a string rather than smth weird)

```
from enum import Enum

class T():
    """Helper class to get mypy to work with TorchTyping and solidify naming conventions as a byproduct.
    
    Examples: 
    - `TT[T.batch, T.pos, T.d_model]`
    - `TT[T.num_components, T.batch_and_pos_dims:...]`
    - `TT[T.d_vocab + T.n_ctx, T.d_model]`
    """

    batch: str = "batch"
    pos: str = "pos"
    head_index: str = "head_index"
    length: str = "length"
    rotary_dim: str = "rotary_dim"
    new_tokens: str = "new_tokens"
    batch_and_pos_dims: str = "batch_and_pos_dims"
    layers_accumulated_over: str = "layers_accumulated_over"
    layers_covered: str = "layers_covered"
    past_kv_pos_offset: str = "past_kv_pos_offset"
    num_components: str = "num_components"
    num_neurons: str = "num_neurons"
    pos_so_far: str = "pos_so_far"
    n_ctx: str = "n_ctx"
    n_heads: str = "n_heads"
    n_layers: str = "n_layers"
    d_vocab: str = "d_vocab"
    d_vocab_out: str = "d_vocab_out"
    d_head: str = "d_head"
    d_mlp: str = "d_mlp"
    d_model: str = "d_model"

    ldim: str = "ldim"
    rdim: str = "rdim"
    new_rdim: str = "new_rdim"
    mdim: str = "mdim"
    leading_dims: str = "leading_dims"
    leading_dims_left: str = "leading_dims_left"
    leading_dims_right: str = "leading_dims_right"

    a: str = "a"
    b: str = "b"
```

**Review by neelnanda-io — CHANGES_REQUESTED** [review]
See above

**Comment by dkamm** [comment]
Oops sorry about that!  I only checked the mypy command.

I think another way to get something like that is to have a singleton with `@dataclass(frozen=True)`?  But I just tried this and it didn't work with mypy unfortunately :(

I'll update the PR to what you have- think it's the best we can do right now

**Comment by dkamm** [comment]
I think it makes sense to add a `T.sum` method for the shapes with addition like `"d_vocab + n_ctx"`.  Writing `T.d_vocab + "+" + T.n_ctx` seems a bit more awkward and error prone (might forget the `"+"`).  It's possible that torchtyping will support checking arithmetic in tensor shapes in the future (see https://github.com/patrick-kidger/torchtyping/issues/2).  This is also why I had the weird `__add__` thing in the enum version

**Review by neelnanda-io — APPROVED** [review]
LGTM pending tests!

**Comment by neelnanda-io** [comment]
Looks good, thanks!

**Comment by neelnanda-io** [comment]
Still failing tests rip `TypeError: type of argument "args"[0] must be a tuple; got str instead` - my guess is that the sum is breaking something? At least in Python 3.7. IMO the sum is not essential, and we can just hardcode the one or two combination strings as a bonus string in the big enum

**Pull request merged**
